apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
  namespace: governance
data:
  conf.yaml: |
    services:
      relay:
        url: http://governance-relay:5000

    decision_logs:
      reporting:
        service: relay
      # FORCE OPA TO UPLOAD EVERY 1 SECOND
      console: true
      upload_size_limit_bytes: 1
      min_delay_seconds: 1
      max_delay_seconds: 1

    status:
      service: relay
