apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: authoritybindings.governance.privatevault.io
spec:
  group: governance.privatevault.io
  scope: Namespaced
  names:
    plural: authoritybindings
    singular: authoritybinding
    kind: AuthorityBinding
    shortNames:
      - abind
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["subject", "roles", "scope"]
              properties:
                subject:
                  type: object
                  required: ["type", "id"]
                  properties:
                    type:
                      type: string
                      enum: ["user", "serviceaccount", "group"]
                    id:
                      type: string
                roles:
                  type: array
                  items:
                    type: string
                    enum: ["Owner", "Approver", "Auditor", "IncidentCommander"]
                scope:
                  type: object
                  required: ["env", "system"]
                  properties:
                    env:
                      type: string
                      description: "prod|staging|dev"
                    system:
                      type: string
                      description: "system identifier e.g. payments|ehr|agents"
                expiresAt:
                  type: string
                  description: "RFC3339 optional expiry"
