apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-authority-resolver
  namespace: governance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pv-authority-resolver
  template:
    metadata:
      labels:
        app: pv-authority-resolver
    spec:
      serviceAccountName: pv-authority-resolver
      containers:
        - name: resolver
          image: ghcr.io/lola0786/pv-authority-resolver:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pv-authority-resolver
  namespace: governance
spec:
  selector:
    app: pv-authority-resolver
  ports:
    - name: http
      port: 8081
      targetPort: 8081
